[versions]
kotlin = "2.3.0"
agp = "8.13.2"
glance = "1.1.1"
compose-guard = "2.4.0"
licensee = "1.14.1"
ktfmt = "0.59"
jdk = "24"
detekt = "1.23.8"
cacheFix = "3.0.3"
spotless = "8.1.0"
sort = "0.16"
dependencyAnalysis = "3.5.1"

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
cacheFix = { id = "org.gradle.android.cache-fix", version.ref = "cacheFix" }
composeGuard = { id = "com.joetr.compose.guard", version.ref = "compose-guard" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version = "0.5.0" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
doctor = { id = "com.osacky.doctor", version = "0.12.1" }
gradle-versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }
sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "sort" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.12.2" }

detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
cacheFix-gradle = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version.ref = "cacheFix" }
sortDependencies-gradle = { module = "com.squareup.sort-dependencies:com.squareup.sort-dependencies.gradle.plugin", version.ref = "sort" }
composeGuard-gradle = { module = "com.joetr.compose.guard:com.joetr.compose.guard.gradle.plugin", version.ref = "compose-guard" }
dependencyAnalysis-gradle = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependencyAnalysis" }

compose-bom = { module = "androidx.compose:compose-bom", version = "2026.01.00" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-material = { module = "androidx.compose.material3:material3" }
compose-colorpicker = { module = "com.github.skydoves:colorpicker-compose", version = "1.1.3" }

glanceTool-configuration = { module = "dev.whosnickdoglio.glance:appwidget-configuration", version = "0.3.0-SNAPSHOT" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
glance-appwidget-testing = { module = "androidx.glance:glance-appwidget-testing", version.ref = "glance" }
glance-material = { module = "androidx.glance:glance-material3", version.ref = "glance" }
glance-testing = { module = "androidx.glance:glance-testing", version.ref = "glance" }
glance-preview = { module = "androidx.glance:glance-preview", version.ref = "glance" }
glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "glance" }

junit = { module = "junit:junit", version = "4.13.2" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.1" }
robolectric = { module = "org.robolectric:robolectric", version = "4.16.1" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }

# Only present to trigger automatic renovate updates
ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }

coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.10.2" }

serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }
immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.4.0" }

desguar = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.5" }

lints-compose = { module = "com.slack.lint.compose:compose-lint-checks", version = "1.4.2" }
